name: ci-spring-boot-workflow
on:
  pull_request:
    branches:
      - development

jobs:
  build-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11','17']
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - run: mvn -B package --file pom.xml