name: ci-spring-boot-workflow
on:
  pull_request:
    branches:
      - development

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - run: mvn -B package --file pom.xml