name: ci-spring-boot-workflow
on: [push]
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - run: mvn -B package --file pom.xml